services:
  hbd-db:
    image: postgres:16.3-bookworm
    container_name: hbd-db
    volumes:
      - hbd-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6684:5432"
  
  hbd-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hbd-backend
    volumes:
      - .:/app
    ports:
      - "8417:8417"
    depends_on:
      - hbd-db
    environment:
      - DB_TYPE=postgres
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - MASTER_KEY=35e150e7ca83247f18cb1a37d61d8e161dddec06027f5db009b34da48c25f1b5

networks:
  default:
    name: hbd-network

volumes:
  hbd-data:
    driver: local
